"""
Protocol-Specific Patterns for IntelligentGapDetector
======================================================
AUTO-GENERATED by backend/protocol_training/pattern_miner.py
Do not edit manually — re-run the pattern miner to regenerate.

Provides:
  - PROTOCOL_FRAME_TEMPLATES: New frame types for protocol content
  - PROTOCOL_MISSING_PATTERNS: Missing info patterns for protocols
  - PROTOCOL_CONTENT_INDICATORS: Regex patterns to detect protocol text
  - is_protocol_content(): Quick heuristic check
"""

import re
from typing import Dict, List, Any, Tuple


# =============================================================================
# PROTOCOL CONTENT DETECTION
# =============================================================================

PROTOCOL_CONTENT_INDICATORS = [
    # Action verbs typical of lab protocols
    r"\b(?:add|adjust|agitate|aliquot|analyze|apply|aspirate|assay|autoclave|blot|boil|buffer|calibrate|cap|centrifuge|clamp|clean|collect|combine|cool|count|culture|cut|decant|denature|detect|dialyze|digest|dilute|discard|disconnect|dispense|dissolve|drain|dry|elute|equilibrate|evaporate|examine|extract|filter|fix|flash|flush|freeze|grind|grow|harvest|heat|homogenize|hybridize|image|immerse|incubate|inject|inoculate|insert|invert|isolate|label|layer|ligate|load|lyse|measure|melt|microcentrifuge|mix|mount|neutralize|observe|open|overlay|passage|pcr|pellet|perfuse|photograph|pipette|plate)\b",
    # Parameter patterns
    r"\d+\.?\d*\s*(?:mM|µM|uM|nM|mg/ml|µg/ml|ng/ml|%\s*(?:v/v|w/v))",
    r"\d+\.?\d*\s*(?:min(?:utes?)?|sec(?:onds?)?|hrs?|hours?)",
    r"-?\d+\.?\d*\s*°?\s*[CF]\b",
    r"\d+[,.]?\d*\s*(?:rpm|RPM|rcf|xg|×g)",
    r"\d+\.?\d*\s*(?:ml|mL|µl|µL|ul|uL|nl|L)",
    r"\d+\.?\d*\s*(?:mg|µg|ug|ng|pg|g|kg)",
    r"pH\s*\d+\.?\d*",
    # Equipment mentions
    r"\b(?:centrifuge|PCR|thermocycler|incubator|spectrophotometer|nanodrop)\b",
    r"\b(?:vortex|sonicator|autoclave|microscope|plate\s+reader)\b",
    r"\b(?:gel\s+electrophoresis|western\s+blot|HPLC|mass\s+spec)\b",
    r"\b(?:fume\s+hood|biosafety\s+cabinet|laminar\s+flow)\b",
    # Reagent/material mentions
    r"\b(?:buffer|solution|reagent|substrate|enzyme|antibody|primer|probe)\b",
    r"\b(?:PBS|DMEM|RPMI|FBS|BSA|EDTA|Tris|HEPES|SDS|TEMED)\b",
    r"\b(?:ethanol|methanol|isopropanol|chloroform|phenol|DMSO)\b",
]

PROTOCOL_CONTENT_COMPILED = [re.compile(p, re.IGNORECASE) for p in PROTOCOL_CONTENT_INDICATORS]


def is_protocol_content(text: str, threshold: int = 5) -> Tuple[bool, float]:
    """
    Heuristic check: does this text look like a scientific protocol?

    Returns (is_protocol, confidence) where confidence is 0.0 to 1.0.
    A text needs at least `threshold` indicator matches to be considered protocol content.
    """
    if not text or len(text) < 50:
        return False, 0.0

    sample = text[:10000]  # Check first 10K chars for speed
    matches = 0
    max_possible = len(PROTOCOL_CONTENT_COMPILED)

    for pattern in PROTOCOL_CONTENT_COMPILED:
        if pattern.search(sample):
            matches += 1

    confidence = min(1.0, matches / max(1, max_possible * 0.6))
    return matches >= threshold, confidence


# =============================================================================
# PROTOCOL FRAME TEMPLATES (merge into FRAME_TEMPLATES)
# =============================================================================

PROTOCOL_FRAME_TEMPLATES = {
    "PROTOCOL_STEP": {
        "required": ["action", "parameters"],
        "optional": ["reagents", "equipment", "duration", "temperature", "expected_result", "notes"],
        "triggers": [
            # Core lab action patterns
            r"(?:pipette|transfer|add|dispense)\s+\d+",
            r"incubate\s+(?:at|for|in)",
            r"centrifuge\s+(?:at|for)",
            r"(?:wash|rinse)\s+(?:with|in|using|\d+\s*(?:times|x))",
            r"elute\s+(?:with|in|into)",
            r"(?:heat|cool|warm)\s+(?:to|at|for)",
            r"vortex\s+(?:for|briefly|vigorously)",
            r"(?:mix|combine|pool)\s+(?:with|together|the)",
            r"(?:resuspend|dissolve|reconstitute)\s+(?:in|with|the)",
            r"(?:filter|strain)\s+(?:through|using|with)",
            r"(?:dilute|concentrate)\s+(?:to|with|the|\d+)",
            r"(?:spin|pellet)\s+(?:at|for|down)",
            r"(?:load|apply|pour)\s+(?:onto|into|the)",
            r"(?:stain|label|probe)\s+(?:with|for|using)",
            r"(?:prepare|make|set up)\s+(?:a|the|fresh)",
            r"(?:store|keep|freeze|thaw)\s+(?:at|in|until)",
            r"(?:remove|discard|aspirate)\s+(?:the|supernatant|media|medium)",
            r"(?:measure|record|note)\s+(?:the|absorbance|concentration|volume)",
            r"(?:dry|air-dry|vacuum-dry|lyophilize)\s+",
            r"(?:sterilize|autoclave|UV-treat)\s+",
            r"run\s+(?:the|a)?\s*(?:gel|PCR|reaction|assay|column)",
            r"set\s+(?:the)?\s*(?:temperature|speed|timer|voltage)",
            r"equilibrate\s+(?:to|at|for|the)",
            r"(?:cut|digest|ligate)\s+(?:with|the|using)",
            r"plate\s+(?:cells?|bacteria|the)",
            r"harvest\s+(?:cells?|the|media)",
        ]
    },
    "REAGENT_USAGE": {
        "required": ["reagent_name", "concentration"],
        "optional": ["volume", "preparation", "storage", "vendor", "catalog_number"],
        "triggers": [
            r"\d+\.?\d*\s*(?:mM|µM|uM|nM|pM|M)\s+",
            r"\d+\.?\d*\s*(?:mg/ml|mg/mL|µg/ml|µg/mL|ug/ml|ng/ml|ng/µl)",
            r"\d+\.?\d*\s*%\s*(?:v/v|w/v|w/w)",
            r"(?:stock|working)\s+(?:solution|concentration)",
            r"(?:final|initial)\s+concentration",
            r"(?:freshly|newly)\s+(?:prepared|made|dissolved)",
            r"(?:dilute|diluted)\s+(?:\d+[:-]\d+|to\s+\d+)",
            r"(?:add|use|prepare)\s+\d+\.?\d*\s*(?:ml|µl|ul|mL|µL|uL|L)",
        ]
    },
    "EQUIPMENT_SETUP": {
        "required": ["equipment", "settings"],
        "optional": ["calibration", "maintenance", "alternatives"],
        "triggers": [
            r"set\s+(?:to|at)\s+\d+",
            r"preheat\s+(?:to|at)\s+\d+",
            r"\d+[,.]?\d*\s*(?:rpm|RPM|rcf|RCF|xg|×g)",
            r"(?:PCR|thermal)\s*cycl(?:er|ing)",
            r"(?:HPLC|GC|LC)[- ](?:MS)?",
            r"(?:plate\s+reader|spectrophotometer|nanodrop)",
            r"(?:flow\s+cytometer|FACS|cell\s+sorter)",
            r"(?:gel\s+(?:box|apparatus)|electrophoresis)",
            r"(?:column|cartridge|membrane|filter)\s+(?:equilibrat|condition|prime|wash)",
        ]
    },
    "SAFETY_PRECAUTION": {
        "required": ["hazard", "precaution"],
        "optional": ["ppe_required", "disposal", "first_aid", "regulatory"],
        "triggers": [
            r"(?:caution|warning|danger|hazard)",
            r"(?:fume\s+hood|chemical\s+hood|laminar\s+flow)",
            r"(?:PPE|personal\s+protective|gloves|goggles|lab\s+coat|face\s+(?:mask|shield))",
            r"(?:toxic|corrosive|flammable|irritant|carcinogen)",
            r"(?:biohazard|biosafety|BSL-?\d|radioactive)",
            r"(?:waste\s+disposal|sharps?\s+container|decontaminat)",
            r"(?:avoid\s+(?:contact|exposure|inhalation|ingestion))",
            r"(?:MSDS|SDS|safety\s+data\s+sheet)",
            r"(?:eye\s+wash|safety\s+shower|first\s+aid)",
            r"(?:do\s+not\s+(?:inhale|ingest|pipette\s+by\s+mouth))",
        ]
    },
    "EXPECTED_RESULT": {
        "required": ["observation", "criteria"],
        "optional": ["troubleshooting", "alternatives", "quantitative_range"],
        "triggers": [
            r"should\s+(?:yield|produce|result|appear|show|give|be)",
            r"(?:expect|expected)\s+(?:to|result|output|yield|band|peak)",
            r"(?:positive|negative)\s+control",
            r"(?:expected|typical|normal)\s+(?:range|value|result|output|yield)",
            r"band\s+(?:at|of|around)\s+\d+",
            r"(?:peak|signal)\s+(?:at|around)\s+\d+",
            r"(?:OD|A)\d{3}\s*(?:=|of|around|~)\s*\d+",
            r"(?:confluence|confluency|density)\s+(?:of|at|~)\s*\d+",
            r"(?:purity|yield|recovery|efficiency)\s+(?:of|>|<|~|around)\s*\d+",
        ]
    },
}


# =============================================================================
# PROTOCOL-SPECIFIC MISSING PATTERNS (merge into MISSING_PATTERNS)
# =============================================================================

PROTOCOL_MISSING_PATTERNS = {
    "VAGUE_PARAMETER": [
        r"\b(?:briefly|gently|vigorously|thoroughly|carefully)\b",
        r"\b(?:overnight|room\s+temperature|ambient\s+temperature|RT)\b",
        r"\b(?:some|several|a\s+few|adequate|sufficient|enough|appropriate)\s+(?:amount|volume|quantity)",
        r"\b(?:small|large|generous|trace)\s+(?:amount|volume|quantity)",
        r"\b(?:warm|cold|hot|cool|lukewarm)\b(?!\s*(?:to|at)\s*\d)",
        r"\b(?:fast|slow|quick|rapid)(?:ly)?\b(?!\s*(?:at|to)\s*\d)",
        r"\b(?:short|long|extended)\s+(?:time|period|incubation|centrifugation)",
        r"\b(?:low|high|medium|moderate)\s+(?:speed|power|voltage|temperature)(?!\s*(?:\(|of|=|:)\s*\d)",
    ],
    "MISSING_CONCENTRATION": [
        r"(?:add|use|prepare|dissolve|dilute)\s+(?:the\s+)?(?:buffer|solution|reagent|antibody|enzyme|substrate|primer|probe)(?!\s*(?:at|to|\(|\d+\s*(?:mM|µM|uM|mg|µg|ng|%)))",
    ],
    "MISSING_DURATION": [
        r"\b(?:incubate|centrifuge|spin|vortex|shake|heat|cool|boil|sonicate|digest|ligate|dry|equilibrate|block|stain|wash)\b(?!.*?(?:\d+\s*(?:min|sec|hr|hour|day|week|s\b|m\b|h\b)))",
    ],
    "MISSING_TEMPERATURE": [
        r"\b(?:incubate|heat|warm|cool|store|freeze|thaw)\b(?!.*?(?:\d+\s*°|\d+\s*degrees|room\s+temp|RT\b|on\s+ice|4\s*°?C|37\s*°?C|-[278]0\s*°?C))",
    ],
    "MISSING_EQUIPMENT_SETTING": [
        r"\b(?:centrifuge|spin)\b(?!.*?(?:\d+\s*(?:rpm|RPM|rcf|RCF|xg|×g)))",
        r"\b(?:run|load)\s+(?:the\s+)?gel\b(?!.*?(?:\d+\s*(?:V|mA|W|volts?|milliamps?|watts?)))",
    ],
    "MISSING_SAFETY_INFO": [
        # Hazardous reagent mentioned without safety context nearby
        r"\b(?:phenol|chloroform|trizol|formaldehyde|paraformaldehyde|acrylamide|ethidium\s+bromide|beta-?mercaptoethanol|sodium\s+azide)\b(?!.*?(?:hood|PPE|gloves|caution|warning|hazard|safety|careful|avoid))",
    ],
    "MISSING_VENDOR_INFO": [
        r"\b(?:antibody|antibodies|primer|primers|enzyme|kit|plasmid|vector|cell\s+line)\b(?!.*?(?:catalog|cat\.?\s*#|cat\.?\s*no|from\s+\w+|purchased|obtained|supplied|provided|\w+®|Thermo|Sigma|Invitrogen|Qiagen|NEB|Promega|Bio-?Rad|Abcam|Santa\s+Cruz|Cell\s+Signaling))",
    ],
}


# =============================================================================
# PROTOCOL QUESTION TEMPLATES (for GroundedQuestionGenerator)
# =============================================================================

PROTOCOL_QUESTION_TEMPLATES = {
    "PROTOCOL_STEP": [
        "What specific {parameters} should be used when performing {action}?",
        "What is the expected result after completing the {action} step?",
        "Are there any critical parameters missing from the {action} procedure?",
        "What equipment settings are needed for {action}?",
    ],
    "REAGENT_USAGE": [
        "What is the exact concentration of {reagent_name} to use?",
        "How should the {reagent_name} solution be prepared and stored?",
        "What is the vendor and catalog number for {reagent_name}?",
        "Are there any substitutes for {reagent_name}?",
    ],
    "EQUIPMENT_SETUP": [
        "What specific settings should {equipment} be configured to?",
        "Does {equipment} need calibration before use? If so, how?",
        "What maintenance is required for {equipment}?",
    ],
    "SAFETY_PRECAUTION": [
        "What PPE is required when handling {hazard}?",
        "What is the proper disposal procedure for {hazard}?",
        "What are the first aid measures if exposed to {hazard}?",
        "Is a fume hood or biosafety cabinet required for this step?",
    ],
    "EXPECTED_RESULT": [
        "What is the expected quantitative range for {observation}?",
        "What troubleshooting steps should be taken if {criteria} is not met?",
        "What does a failed result look like, and what are the likely causes?",
    ],
}
